name: Add Blog Request

  on:
    repository_dispatch:
      types: [blog-request]

  jobs:
    add-request:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Add request to BLOG_REQUESTS.md
          run: |
            REQUEST="${{ github.event.client_payload.request }}"
            TIMESTAMP="${{ github.event.client_payload.timestamp }}"
            echo "📝 Adding request: $REQUEST"
            echo "🕐 Timestamp: $TIMESTAMP"
            node add-request-from-webhook.js "$REQUEST"

        - name: Commit and push changes
          run: |
            git config --local user.email "noreply@anthropic.com"
            git config --local user.name "Claude (Blog Request Bot)"
            git add BLOG_REQUESTS.md
            git commit -m "Add blog request via web form

            Request: ${{ github.event.client_payload.request }}
            Timestamp: ${{ github.event.client_payload.timestamp }}

            Automated via repository_dispatch" || echo "No changes to
  commit"
            git push
